
server:
  port: ${PORT:8080}

spring:
  application:
    name: user-management-service
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      auto-index-creation: true
#      custom-converters: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: shiva2000shivam@gmail.com
    password: abvcjhgfdhhgfghfsfh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp
          timeout: 5000
          write-timeout: 5000
          connection-timeout: 5000

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-management-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.snp.dev.user_management_service.serializers.EmailMessageSerializer
      properties:
        retries: 3
        acks: all
        delivery.timeout.ms: 30000
        request.timeout.ms: 15000


  redis:
    host: localhost
    port: 6379

management:
  endpoints:
    web:
      exposure:
        include: "*"

  health:
    show-details: always


jwt:
  secret: "N5hDo6X+wbM/U5wfDdq68oLUUHyTHA/A7pCpIMJWtT1ObBd4IYRI+CxrgEGnsreNghenpMmeUHUcPm4SoRO5sw=="
  expiration: 86400000 # 24 hours
  issuer: user-management-service

app:
  otp:
    length: 6
    expiry-minutes: 5
  mfa:
    issuer: UserManagement
  rate-limit:
    signup: 3
    window: 1h
  super-admin:
    initial-email: superadmin@example.com
    initial-password: ChangeMe123!
  kafka:
    topics:
      email: user-emails
    email:
      enabled: false
    consumer-enabled: false
  audit-logs:
    enabled: true
  jwt:
    passwordResetSecret: "N5hPo20+wbM/U5wfDdq68oLUUHyTHA/A7pCpIMJWtT1ObBd4IYGD+CxrgEGnsreNghenpMmeUHUcPm4SoRO5sw=="
    passwordResetTokenExpirationMs: 86400000 # 24 hours

logging:
  level:
    root: INFO
    org.springframework: INFO
#    org.springframework: DEBUG
    com.snp.dev.user-management-service: DEBUG

#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG